#!/usr/bin/env python3
"""Reconcile Chromium's std source list with the rustc actually installed.

build/rust/std/rules/BUILD.gn is generated by gnrt against the rustc Chromium
bundles and names every file of std by hand. A rustc from a different revision
breaks the list in both directions:

  * names whose files are gone -- ninja stops with "missing and no known rule
    to make it";
  * files the new std has that the list does not name -- rustc_wrapper.py
    stops with "Rust source file or input not in GN sources".

Both are fixed here by comparing each `sources = [...]` block against the
directory its own entries already point into. Nothing is invented: a name is
added only if a sibling of an already-listed file, and removed only if the
file is absent.
"""
import os
import re
import sys

src = sys.argv[1]
p = os.path.join(src, "build/rust/std/rules/BUILD.gn")

lines = open(p).read().split("\n")
out = []
dropped = []
added = []

i = 0
while i < len(lines):
    # An empty one-line `inputs = []` needs filling too: the .md files
    # rustdoc includes live there, and gnrt writes the list empty when the
    # bundled std had none in that crate.
    empty = re.match(r"(\s*)(sources|inputs) = \[\]\s*$", lines[i])
    if empty:
        indent, kind = empty.group(1), empty.group(2)
        lines[i] = "%s%s = [" % (indent, kind)
        lines.insert(i + 1, "%s]" % indent)

    block_kind = re.match(r"\s*(sources|inputs) = \[\s*$", lines[i])
    if not block_kind:
        out.append(lines[i])
        i += 1
        continue
    kind = block_kind.group(1)

    out.append(lines[i])
    j = i + 1
    entries = []
    while j < len(lines) and not re.match(r"\s*\]\s*$", lines[j]):
        entries.append(lines[j])
        j += 1

    listed = []
    for e in entries:
        m = re.match(r'\s*"//([^"]+)",\s*$', e)
        if m:
            listed.append(m.group(1))
    known = {os.path.normpath(x) for x in listed}

    # Keep only what exists.
    kept = []
    for e in entries:
        m = re.match(r'\s*"//([^"]+)",\s*$', e)
        if m and not os.path.exists(os.path.join(src, m.group(1))):
            dropped.append(m.group(1))
            continue
        kept.append(e)

    # Add siblings: any file of the same extension in a directory this block
    # already lists, that the block does not name. That keeps the scan inside
    # the crate the block is for and never wanders into vendor/.
    dirs = {os.path.dirname(x) for x in listed}

    # Scanning only the directories already listed misses whole directories
    # a different rustc revision has added -- compiler-builtins grew a
    # libm/src/math/relaxed/, core keeps .md files under sync/ that no source
    # in the block points at. Walk the crate instead. The crate root comes
    # from the first entry that names one.
    # The crate root is the shortest directory prefix all the block's own
    # entries share, walked only that far. Taking `library/<name>` instead
    # would sweep in vendor/, which is thousands of files this target does
    # not build.
    # gnrt writes some entries with ../.. in them -- compiler-builtins
    # reaches its sibling libm that way -- so normalise before deciding what
    # directory a block covers.
    # Walk each directory the block already names, and one level below it.
    # That picks up a subdirectory a newer rustc has added -- libm grew a
    # math/relaxed/ -- without wandering up into vendor/, which is thousands
    # of files this target does not build.
    roots = {os.path.normpath(os.path.dirname(x)) for x in listed}
    dirs = set()
    for r in roots:
        full = os.path.join(src, r)
        if not os.path.isdir(full):
            continue
        dirs.add(r)
        for entry in sorted(os.listdir(full)):
            sub = os.path.join(full, entry)
            if os.path.isdir(sub):
                dirs.add(os.path.join(r, entry))
    extra = []
    for d in sorted(dirs):
        full = os.path.join(src, d)
        if not os.path.isdir(full):
            continue
        for f in sorted(os.listdir(full)):
            rel = os.path.join(d, f)
            if not os.path.isfile(os.path.join(src, rel)):
                continue
            # gn will not take a .md in `sources`, but `inputs` holds both:
            # gnrt puts the .md files rustdoc includes there, and also the
            # .rs of crates reached sideways, as compiler-builtins reaches
            # its sibling libm. So restrict only the sources side.
            wanted = (".rs",) if kind == "sources" else (".rs", ".md")
            if not f.endswith(wanted):
                continue
            if os.path.normpath(rel) not in known:
                extra.append(rel)

    indent = re.match(r"(\s*)", entries[0]).group(1) if entries else "    "
    for e in kept:
        out.append(e)
    for e in extra:
        out.append('%s"//%s",' % (indent, e))
        added.append(e)

    out.append(lines[j] if j < len(lines) else "  ]")
    i = j + 1

open(p, "w").write("\n".join(out))

# panic_abort's dependency on alloc. Chromium's generated rules give it :alloc
# only under is_android, matching the rustc it bundles. In the revision built
# here panic_abort uses alloc::boxed::Box and alloc::panicking unconditionally,
# so without the dependency it fails with "cannot find module or crate `alloc`"
# on every other platform. gnrt would regenerate this correctly; adding it is
# the same conclusion reached by hand.
text = open(p).read()
old_dep = """  if (is_android) {
    deps += [
      ":alloc",
      ":libc",
    ]
  }"""
new_dep = """  deps += [ ":alloc" ]
  if (is_android) {
    deps += [ ":libc" ]
  }"""
if old_dep in text:
    open(p, "w").write(text.replace(old_dep, new_dep, 1))
    print("  panic_abort: depends on alloc unconditionally")
print("  %d removed, %d added" % (len(dropped), len(added)))
P = "third_party/rust-toolchain/lib/rustlib/src/rust/library/"
for d in dropped[:3]:
    print("    - " + d.replace(P, ""))
for a in added[:5]:
    print("    + " + a.replace(P, ""))
if len(added) > 5:
    print("    ... and %d more" % (len(added) - 5))
