#!/bin/bash
#
# Cross-build ninja and gn for Haiku arm64, and package them.
#
# Step 2 of the Chromium arm64 port: Chromium is generated by gn and built by
# ninja, and both have to run on the target. gn already knows Haiku; ninja
# does not, and needs one small fix.
#
set -e
GB="${GNBUILD_DIR:-/root/gnbuild}"
G="${RENKU_GEN:-/root/gen-kd}"
PB="${PYBUILD_DIR:-/root/pybuild}"
CT=/root/gen-arm64/cross-tools-arm64/bin/aarch64-unknown-haiku
NINJA_V=1.12.1
JOBS="${JOBS:-8}"
PKG=$(find "$G/objects/linux" -name package -type f -perm -u+x 2>/dev/null | head -1)

log() { printf '\n=== %s\n' "$*"; }

# The cross gcc is configured with --with-sysroot and already knows Haiku's
# whole header layout, so pointing it at the assembled sysroot is all the
# configuration these two need.
ln -sfn "$PB/sysroot" /root/gen-arm64/cross-tools-arm64/sysroot

mkdir -p "$GB"
cd "$GB"

# --- ninja --------------------------------------------------------------
log "ninja $NINJA_V"
[ -f ninja.tar.gz ] || wget -q "https://github.com/ninja-build/ninja/archive/refs/tags/v$NINJA_V.tar.gz" -O ninja.tar.gz
[ -d "ninja-$NINJA_V" ] || tar xzf ninja.tar.gz

# Haiku defines CPU_COUNT but has no sched_getaffinity, so ninja picks the
# Linux branch of GetProcessorCount and fails to link. Excluding Haiku there
# drops it onto the sysconf(_SC_NPROCESSORS_ONLN) fallback just below.
python3 - "$GB/ninja-$NINJA_V/src/util.cc" <<'PY'
import sys
p = sys.argv[1]
s = open(p).read()
if "__HAIKU__" not in s.split("GetLoadAverage")[0]:
    old = "#elif defined(CPU_COUNT)\n  cpu_set_t set;"
    new = ("#elif defined(CPU_COUNT) && !defined(__HAIKU__)\n"
           "  // Haiku defines CPU_COUNT but has no sched_getaffinity; it falls\n"
           "  // through to the sysconf(_SC_NPROCESSORS_ONLN) path below.\n"
           "  cpu_set_t set;")
    assert s.count(old) == 1, "ninja util.cc does not look as expected"
    open(p, "w").write(s.replace(old, new))
    print("  patched util.cc for Haiku")
else:
    print("  util.cc already patched")
PY

cd "$GB/ninja-$NINJA_V"
# configure.py has no Haiku platform and its --bootstrap would try to run the
# binary it just built, which cannot work when cross-compiling. Ninja is a
# flat set of translation units, so compile them directly.
NINJA_SRCS="src/build.cc src/build_log.cc src/clean.cc src/clparser.cc
	src/dyndep.cc src/dyndep_parser.cc src/debug_flags.cc src/depfile_parser.cc
	src/deps_log.cc src/disk_interface.cc src/edit_distance.cc src/eval_env.cc
	src/graph.cc src/graphviz.cc src/json.cc src/lexer.cc src/line_printer.cc
	src/manifest_parser.cc src/metrics.cc src/missing_deps.cc src/parser.cc
	src/state.cc src/status.cc src/string_piece_util.cc src/util.cc
	src/version.cc src/subprocess-posix.cc src/ninja.cc"
$CT-g++ -O2 -std=c++11 -D_DEFAULT_SOURCE -D_FILE_OFFSET_BITS=64 -DUSE_PPOLL \
	-DNINJA_PYTHON='"python3"' $NINJA_SRCS -o "$GB/ninja"
echo "  built $GB/ninja"

# A host ninja is needed to run gn's generated build.
if [ ! -x "$GB/ninja-host/ninja" ]; then
	log "host ninja"
	rm -rf "$GB/ninja-host"
	cp -r "$GB/ninja-$NINJA_V" "$GB/ninja-host"
	( cd "$GB/ninja-host" && python3 configure.py --bootstrap >/dev/null )
fi

# --- gn -----------------------------------------------------------------
log "gn"
cd "$GB"
[ -d gn ] || git clone -q --depth 1 https://gn.googlesource.com/gn
cd gn
rm -rf out-arm64
# --allow-warnings: a -Werror=comment trips on a multi-line comment in
# header_checker.h with this gcc.
# --no-last-commit-position: gen.py derives it from "git describe", which a
# shallow clone cannot answer; the header is written by hand below.
CC=$CT-gcc CXX=$CT-g++ AR=$CT-ar LD=$CT-g++ \
	python3 build/gen.py --platform haiku --host linux \
		--out-path out-arm64 --no-last-commit-position \
		--no-static-libstdc++ --allow-warnings
REV=$(git rev-parse --short=12 HEAD)
cat > out-arm64/last_commit_position.h <<EOF
#ifndef OUT_LAST_COMMIT_POSITION_H_
#define OUT_LAST_COMMIT_POSITION_H_
#define LAST_COMMIT_POSITION_NUM 0
#define LAST_COMMIT_POSITION "0 ($REV)"
#endif
EOF
# The gn target itself; not "all", whose integration tests run the arm64
# binary on the host and segfault, as any cross build would.
"$GB/ninja-host/ninja" -C out-arm64 -j"$JOBS" gn
echo "  built $GB/gn/out-arm64/gn"

# --- package ------------------------------------------------------------
log "packaging"
ST="$GB/stage"
rm -rf "$ST"
mkdir -p "$ST/boot/system/bin" "$ST/boot/system/data/licenses"
cp "$GB/ninja" "$ST/boot/system/bin/ninja"
cp "$GB/gn/out-arm64/gn" "$ST/boot/system/bin/gn"
$CT-strip --strip-unneeded "$ST/boot/system/bin/ninja" "$ST/boot/system/bin/gn"
HL=/root/haiku-arm64/data/system/data/licenses
cp "$HL/Apache v2" "$ST/boot/system/data/licenses/Apache v2"
cp "$HL/BSD (3-clause)" "$ST/boot/system/data/licenses/BSD (3-clause)"

cat > "$ST/boot/system/.PackageInfo" <<EOF
name			gn_ninja
version			1.12.1-1
architecture		arm64
summary			"The gn meta-build system and the ninja build tool"
description		"gn and ninja, cross-compiled for Haiku arm64. Chromium is
generated by gn and built by ninja, and both have to run on the target."
packager		"The RENKU project"
vendor			"The RENKU project"
licenses {
	"Apache v2"
	"BSD (3-clause)"
}
copyrights {
	"2011-2025 Google Inc. (gn)"
	"2011-2025 Google Inc. (ninja)"
}
provides {
	gn_ninja = 1.12.1
	cmd:ninja = 1.12.1
	cmd:gn = 1.12.1
}
requires {
	haiku
}
urls {
	"https://gn.googlesource.com/gn"
	"https://ninja-build.org/"
}
EOF

OUT="${1:-$GB/gn_ninja-1.12.1-1-arm64.hpkg}"
rm -f "$OUT"
( cd "$ST/boot/system" && "$PKG" create -q "$OUT" )
echo "built $OUT ($(du -h "$OUT" | cut -f1))"
